import type { LanguageCode } from './types/language';

export const DEFAULT_DILIGENCE_PUSH_MAX = 3;

export const DILIGENCE_FALLBACK_TEXT: Readonly<Record<LanguageCode, string>> = {
  zh: [
    '你扪心自问（做一次 FBR），差遣牒已经包含足够明确的目标定义了吗？',
    '',
    '如果没有，`!?@human` 诉请人类给出足够清晰的目标。',
    '',
    '如果目标已经清晰定义，那么你已经完成了所有目标吗？',
    '',
    '如果已经完成，`!?@human` 诉请人类验收。',
    '',
    '如果尚未完成，优先直接确定并执行下一步最优行动项（调用工具或诉请队友）。仅当“下一步不清晰/难以决策”时，才发起一次 `!?@self` 扪心自问（FBR）；收齐该次回贴后，立即把结论落地为可执行动作并开始执行，不要只汇报决定。',
    '',
    '当你确信自己不该或者不能自主继续工作时，立即 `!?@human` 诉请人类确认相关问题或者指出工作方向。',
    '',
    '---',
    '',
    '**注意**：',
    '',
    '扪心自问时，自诉请正文需要包含对当前状况的完整事实性总结（但不要包含差遣牒已有内容）；`!?@self` 发起后不要立即下最终行动决策，先等回贴再综合。综合完成后必须立刻执行已确定行动（工具调用/诉请队友），避免停留在“仅汇报决定”的状态。',
    '',
    '队友如果回复 “将要/可以” 做 XXX 的，你要审视祂所说是否符合整体/分项任务目标，是否值得继续：',
    '',
    '- 如果祂建议的事情可做可不做，那么就可以忽略，不以琐碎小事安排工作。',
    '- 如果值得继续，你可加以纠正或鼓励，并立即诉请其继续，不要留祂停在那里等待指令，这是不可接受的。',
  ].join('\n'),
  en: [
    'Do a self-check (run one FBR): does the Taskdoc already contain a sufficiently clear goal definition?',
    '',
    'If not, use `!?@human` to ask for a sufficiently clear goal.',
    '',
    'If the goal is already clearly defined, ask: have you completed all goals?',
    '',
    'If yes, use `!?@human` to request acceptance.',
    '',
    'If not complete, first determine and execute the best next action (tool call or teammate tellask). Use `!?@self` FBR only when the next move is unclear or hard to decide; after feedback from that FBR run is collected, immediately turn the conclusion into executable action and start execution. Do not stop at reporting a decision.',
    '',
    'When you are convinced you should not or cannot continue autonomously, immediately use `!?@human` to confirm the relevant issue or provide direction.',
    '',
    '---',
    '',
    '**Notes**:',
    '',
    'When running FBR, the self-tellask body must include a complete factual summary of the current situation (but do not repeat information already present in the Taskdoc). After `!?@self`, do not finalize the next action immediately; wait for feedback first, then synthesize. Once synthesized, immediately execute the chosen action (tool call / teammate tellask), and avoid staying in a “decision report only” state.',
    '',
    'If a teammate replies that they “will/can do X”, examine whether it aligns with the overall/sub-task goals and is worth continuing:',
    '',
    '- If it is optional and low impact, ignore it instead of assigning trivial work.',
    '- If it is worth continuing, correct or encourage as needed and immediately tellask them to continue; leaving them idle and waiting for instructions is unacceptable.',
  ].join('\n'),
};
