import type { LanguageCode } from './types/language';

export const DEFAULT_DILIGENCE_PUSH_MAX = 3;

export const DILIGENCE_FALLBACK_TEXT: Readonly<Record<LanguageCode, string>> = {
  zh: [
    '先直接判断：差遣牒已经包含足够明确的目标定义了吗？',
    '',
    '如果没有，使用 `askHuman` 请求人类给出足够清晰的目标。',
    '',
    '如果目标已经清晰定义，那么你已经完成了所有目标吗？',
    '',
    '如果已经完成，使用 `askHuman` 请求人类验收。',
    '',
    '如果尚未完成，优先直接确定并执行下一步最优行动项（调用工具或诉请队友），并立即开始执行，不要只汇报决定。',
    '',
    '当你确信自己不该或者不能自主继续工作时，立即使用 `askHuman` 请求人类确认相关问题或者指出工作方向。',
    '',
    '---',
    '',
    '**注意**：',
    '',
    '一旦你已经判断出下一步，就必须立刻把结论落地为可执行动作（工具调用/诉请队友），避免停留在“仅汇报决定”的状态。',
    '',
    '队友如果回复 “将要/可以” 做 XXX 的，你要审视祂所说是否符合整体/分项任务目标，是否值得继续：',
    '- 如果祂建议的事情可做可不做，那么就可以忽略，不以琐碎小事安排工作。',
    '- 如果值得继续，你可加以纠正或鼓励，并立即诉请其继续，不要留祂停在那里等待指令，这是不可接受的。',
    '',
    '系统会在首次出现“尚未收到反馈、仍在执行中的诉请”时自动添加提醒项，并在状态变化时自动刷新。它只是系统状态窗：内容不可手改；非 0 路进行中时不可删除，0 路时可手动删除。',
    '',
    '当该提醒项明确写出“当前没有任何执行中的诉请、没有其祂智能体在后台工作”时，任何“继续等待”的想法和行为都是错误的；如果你已经明确知晓这点，可手动删除该提醒项以免碍眼。',
    '',
    '同理，若不存在“⏳ 进行中诉请（共 N 路，自动维护；仅 0 路时可手动删除）”这类提醒项，或某条历史诉请未出现在该提醒项中，都表示当前没有可等待的进行中诉请（通常代表该轮已回贴或已结束）；“继续等待”是错误动作，必须立即执行下一步：本地动作，或使用同一个 `sessionSlug` 再次调用 `tellask` 向对应队友发起下一轮诉请。',
    '',
    '若某一路仍在进行中的诉请已经过时、需要纠偏，或希望它提前收口，不要试图删除提醒项来“终止”它。非 0 路时误删会被拒绝，并返回引导文案。正确动作只有一个：更新那一路特定诉请的“任务安排”（对长线诉请复用同一 `sessionSlug` 再发 `tellask`），让对应主理人按最新安排自行最终回复并自然结束。',
    '',
    '特别注意：一次性诉请（`tellaskSessionless`）没有“更新任务安排”的通道；你不能靠再开一个新的 `tellaskSessionless` 去要求旧的一次性支线停止，那只会再创建一个新的瞬态支线。若后续可能需要改要求/提前收口，应从一开始就使用带 `sessionSlug` 的 `tellask`。',
  ].join('\n'),
  en: [
    'First judge directly: does the Taskdoc already contain a sufficiently clear goal definition?',
    '',
    'If not, use `askHuman` to request a sufficiently clear goal.',
    '',
    'If the goal is already clearly defined, ask: have you completed all goals?',
    '',
    'If yes, use `askHuman` to request acceptance.',
    '',
    'If not complete, first determine the best next action (tool call or teammate tellask), and start executing it immediately. Do not stop at reporting a decision.',
    '',
    'When you are convinced you should not or cannot continue autonomously, immediately use `askHuman` to confirm the relevant issue or provide direction.',
    '',
    '---',
    '',
    '**Notes**:',
    '',
    'Once you have determined the next move, immediately turn that conclusion into executable action (tool call / teammate tellask), and avoid staying in a “decision report only” state.',
    '',
    'If a teammate replies that they “will/can do X”, examine whether it aligns with the overall/sub-task goals and is worth continuing:',
    '- If it is optional and low impact, ignore it instead of assigning trivial work.',
    '- If it is worth continuing, correct or encourage as needed and immediately tellask them to continue; leaving them idle and waiting for instructions is unacceptable.',
    '',
    'The system auto-adds this reminder when still-running Tellasks first appear and auto-refreshes it as status changes. It is only a system status window: its content is not hand-editable; while any Tellask is active it is not deletable, and at zero in-flight it may be deleted manually.',
    '',
    'When this reminder explicitly says there are no in-flight Tellasks and no agents working in the background, any “keep waiting” thought or behavior is wrong; if you clearly know this, you may delete the reminder manually to reduce noise.',
    '',
    'Likewise, if a “⏳ In-flight Tellasks (N total, auto-maintained; manually deletable only at zero in-flight)” reminder is absent, or a historical Tellask is not listed in that reminder, there is no waitable in-flight Tellask for it at the moment (usually the previous round has replied or ended). “Keep waiting” is a wrong action; execute the next step immediately: local action, or launch a new Tellask round to the same teammate via `tellask` with the same `sessionSlug`.',
    '',
    'If an in-flight Tellask becomes outdated, needs correction, or should wrap up earlier, do not try to “terminate” it by deleting the reminder. Mistaken deletion while non-zero in-flight will be rejected with guidance. The correct action is to update that specific Tellask’s assignment instead (for a sessioned Tellask, send another `tellask` with the same `sessionSlug`) so the responder can deliver a final reply naturally under the latest assignment.',
    '',
    'Important: a one-shot Tellask (`tellaskSessionless`) has no assignment-update channel. You cannot open another `tellaskSessionless` to tell the earlier one-shot Side Dialog to stop; that only creates another transient Side Dialog. If later correction or earlier wrap-up may be needed, choose `tellask` with a `sessionSlug` from the start.',
  ].join('\n'),
};
